export const API_URL = 'https://api.unsplash.com'
export const API_URL_AUTH = 'https://unsplash.com/oauth/authorize'
export const API_URL_PHOTOS = `${API_URL}/photos`
export const API_URL_TOKEN = 'https://unsplash.com/oauth/token'
export const ACCESS_KEY = 'CTNG97Ng6fT1uIQ5b6vIKIkck_K2eWOFbOsCoh7ElOk'
export const SECRET_KEY = '_vxo6TYuZBau5NO2NW6LfLX7qCGb5VbCV5iLCa-Y_Ok'
export const REDIRECT_URI = 'http://127.0.0.1:5500/'
export const RESPONSE_TYPE = 'code'
export const SCOPE = 'public read_user read_photos write_likes'
